- name: Macos workstation playbook
  hosts: foo
  connection: local
  gather_facts: true
  tasks:
    - name: Get OS Version
      ansible.builtin.debug: msg="{{ ansible_distribution }}"
    - name: Create local bin directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/bin'
        owner: '{{ ansible_env.USER }}'
        state: directory
        mode: "0755"
    - block:
        - name: Escalate priviledge for brew
          ansible.builtin.command:
            cmd: /usr/bin/true
          become: true
        - name: Install Homebrew
          ansible.builtin.shell:
            cmd: hash brew 2>/dev/null || NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        - name: Tap Jira CLI repository
          community.general.homebrew_tap:
            name: ankitpokhrel/jira-cli
            state: present
          when: lookup('env', 'WS_EXTRA') is defined
        - name: Tap emacs repository
          community.general.homebrew_tap:
            name: railwaycat/emacsmacport
            state: present
        - name: Check if Google Chrome is installed
          ansible.builtin.command:
            cmd: test -d /Applications/Google\ Chrome.app
          register: googlechromedir
        - community.general.homebrew:
            state: present
            name: homebrew/cask/google-chrome
          when: googlechromedir.rc != 0
        - community.general.homebrew:
            state: latest
            update_homebrew: true
            name:
              - bash
              - bash-completion@2
              - coreutils
              - emacs-mac
              - findutils
              - gawk
              - gh
              - git
              - gnu-sed
              - gnu-tar
              - google-chrome
              - grep
              - gunzip
              - htop
              - ispell
              - jq
              - pre-commit
              - python
              - shellcheck
              - unzip
              - yamllint
              - yq
        - community.general.homebrew:
            state: latest
            update_homebrew: true
            name:
              - ansible
              - awscli
              - gh
              - go
              - groovy
              - jenkins-lts
              - nmap
              - node
              - openjdk
              - openssl@1.1
              - pnpm
              - pstree
              - telnet
              - terraform
              - unzip
              - virtualenv
          when: lookup('env', 'WS_PLUS') is defined
        - community.general.homebrew:
            state: latest
            update_homebrew: true
            name:
              - argocd
              - docker-compose
              - git-lfs
              - gradle
              - helm
              - jupyterlab
              - kube-ps1
              - kubectx
              - kubernetes-cli
              - kustomize
              - maven
              - minikube
              - ncurses
              - openjdk@11
              - openjdk@8
              - openssl@1.1
              - p11-kit
              - packer
              - pkg-config
              - pre-commit
              - qemu
              - shfmt
              - six
              - snappy
              - sqlite
              - tree
              - watch
              - xz
              - yarn
              - yq
          when: lookup('env', 'WS_EXTRA') is defined
        - name: Clone dotfile repo
          ansible.builtin.git:
            repo: https://github.com/lewars/dotfiles.git
            dest: '{{ ansible_env.HOME }}/git/dotfiles'
            update: true
        - name: Install dot file
          ansible.builtin.command:
            cmd: make
            chdir: '{{ ansible_env.HOME }}/git/dotfiles'
            creates:
              - '{{ ansible_env.HOME }}/.bashrc'
              - '{{ ansible_env.HOME }}/.gitconfig'
              - '{{ ansible_env.HOME }}/.dotfiles'
              - '{{ ansible_env.HOME }}/.emacs'
        - name: Create a bin dir in home directory
          ansible.builtin.file:
            path: '{{ ansible_env.HOME }}/bin'
            state: directory
            mode: "0700"
        - name: Download and install gcloud sdk
          ansible.builtin.unarchive:
            src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-413.0.0-darwin-arm.tar.gz
            dest: '{{ ansible_env.HOME }}/bin'
            remote_src: true
          when: lookup('env', 'WS_EXTRA') is defined
        - name: Install gcloud cli
          ansible.builtin.command:
            cmd: '{{ ansible_env.HOME }}/bin/google-cloud-sdk/install.sh --usage-reporting false --bash-completion true --path-update true --additional-components kubectl -q'
          when: lookup('env', 'WS_EXTRA') is defined
        - name: Check if IntelliJ is installed
          ansible.builtin.command:
            cmd: test -d /Applications/IntelliJ\ IDEA.app
          register: intelljdir
          when: lookup('env', 'WS_CODE') is defined
        - name: Check if Intell J is isntalled
          community.general.homebrew:
            state: present
            name: homebrew/cask/intellij-idea
          when: intelljdir.rc != 0 and lookup('env', 'WS_CODE') is defined
        - name: Check if iTerm is installed
          ansible.builtin.command:
            cmd: test -d /Applications/iTerm.app
          register: itermdir
        - community.general.homebrew:
            state: present
            name: homebrew/cask/iterm2
          when: itermdir.rc != 0
        - name: Check if macfuse is installed
          ansible.builtin.command:
            cmd: brew info macfuse >/dev/null
          register: macfuseinfo
          when: lookup('env', 'WS_EXTREAM') is defined
        - community.general.homebrew:
            state: present
            name: homebrew/cask/macfuse
          when: macfuseinfo.rc != 0 and lookup('env', 'WS_EXTREAM') is defined
        - name: Check if VLC is installed
          ansible.builtin.command:
            cmd: test -d /Applications/VLC.app
          register: vlcinfo
          when: lookup('env', 'WS_EXTRA') is defined
        - community.general.homebrew:
            state: present
            name: homebrew/cask/vlc
          when: vlcinfo.rc != 0 and lookup('env', 'WS_EXTRA') is defined
        - name: Check if Loopback is installed
          ansible.builtin.command:
            cmd: test -d /Applications/Loopback.app
          register: loopbackdir
          when: vlcinfo.rc != 0 and lookup('env', 'WS_EXTRA') is defined
        - community.general.homebrew:
            state: present
            name: loopback
          when: loopbackdir.rc != 0 and lookup('env', 'WS_EXTRA') is defined
